// Generated by Wrangler by running `wrangler types`

interface Env {
	SUPABASE_URL: "https://xxxxx.supabase.co";
	SUPABASE_ANON_KEY: "xxxxx.xxxxx.xxxxx";
	SUPABASE_SERVICE_ROLE_KEY: string;
	SUPABASE_JWT_SECRET: string;
	DB: D1Database;
}
